"""Curated waste knowledge base.

Guidance follows common practice in Indian cities (Solid Waste Management Rules 2016 three-stream
segregation: wet / dry / domestic hazardous; E-Waste (Management) Rules 2022). Rules differ between
municipalities, so wording stays at "generally" level and `local_note` flags where to check locally.
Admins can edit everything here from the dashboard after seeding.
"""

CATEGORIES = [
    {
        "slug": "plastic", "name": "Plastic", "name_hi": "प्लास्टिक", "emoji": "🧴", "color": "#2a78d6",
        "short": "Bottles, packets, containers, bags", "short_hi": "बोतलें, पैकेट, डिब्बे, थैलियाँ",
        "collectable": True, "donatable": False, "points_per_kg": 10, "partner_rate_per_kg": 4.0,
        "co2e_factor": 1.5, "sort_order": 1,
        "guidance": {
            "en": {
                "do": ["Empty it and give food containers a quick rinse", "Let it dry before storing",
                       "Squash bottles to save space"],
                "dont": ["Don't leave food or liquid inside", "Don't burn plastic",
                         "Don't mix it with wet kitchen waste"],
                "why": "Clean, dry plastic can be sorted and recycled. Food left inside makes the whole bag "
                       "dirty, and dirty plastic usually ends up in a landfill.",
            },
            "hi": {
                "do": ["खाली करें और खाने के डिब्बों को हल्का धो लें", "रखने से पहले सुखा लें",
                       "जगह बचाने के लिए बोतलें दबा दें"],
                "dont": ["अंदर खाना या तरल न छोड़ें", "प्लास्टिक कभी न जलाएँ", "गीले कचरे के साथ न मिलाएँ"],
                "why": "साफ़ और सूखा प्लास्टिक छाँटकर रीसायकल हो सकता है। गंदा प्लास्टिक अक्सर लैंडफिल में जाता है।",
            },
        },
    },
    {
        "slug": "paper", "name": "Paper & Cardboard", "name_hi": "कागज़ और गत्ता", "emoji": "📦", "color": "#eb6834",
        "short": "Newspaper, boxes, books, notebooks", "short_hi": "अख़बार, डिब्बे, किताबें, कॉपियाँ",
        "collectable": True, "donatable": True, "points_per_kg": 6, "partner_rate_per_kg": 3.0,
        "co2e_factor": 0.9, "sort_order": 2,
        "guidance": {
            "en": {
                "do": ["Keep paper dry", "Flatten cardboard boxes", "Tear off greasy or food-stained parts",
                       "Donate books in good condition"],
                "dont": ["Don't include wet or oily paper", "Don't include used tissues",
                         "Don't tie paper with plastic tape if you can avoid it"],
                "why": "Paper fibres can be recycled many times, but grease and water weaken them and "
                       "spoil the whole batch.",
            },
            "hi": {
                "do": ["कागज़ सूखा रखें", "गत्ते के डिब्बे चपटे कर दें", "तेल या खाने वाले हिस्से फाड़कर अलग करें",
                       "अच्छी हालत की किताबें दान करें"],
                "dont": ["गीला या तेल वाला कागज़ न डालें", "इस्तेमाल किए टिश्यू न डालें"],
                "why": "कागज़ कई बार रीसायकल हो सकता है, पर तेल और पानी उसे खराब कर देते हैं।",
            },
        },
    },
    {
        "slug": "metal", "name": "Metal", "name_hi": "धातु", "emoji": "🥫", "color": "#1baf7a",
        "short": "Cans, foil, old utensils, scrap", "short_hi": "कैन, फॉयल, पुराने बर्तन, कबाड़",
        "collectable": True, "donatable": False, "points_per_kg": 12, "partner_rate_per_kg": 5.0,
        "co2e_factor": 2.5, "sort_order": 3,
        "guidance": {
            "en": {
                "do": ["Rinse food cans", "Make sure spray cans are completely empty",
                       "Put sharp lids inside the can"],
                "dont": ["Don't include batteries (they are e-waste)", "Don't pierce or crush spray cans"],
                "why": "Metals can be melted and reused again and again, which saves a lot of mining and energy.",
            },
            "hi": {
                "do": ["खाने के कैन धो लें", "स्प्रे कैन पूरी तरह खाली हों", "धारदार ढक्कन कैन के अंदर रखें"],
                "dont": ["बैटरी न डालें (वह ई-कचरा है)", "स्प्रे कैन में छेद न करें और न दबाएँ"],
                "why": "धातु को बार-बार पिघलाकर दोबारा इस्तेमाल किया जा सकता है।",
            },
        },
    },
    {
        "slug": "glass", "name": "Glass", "name_hi": "काँच", "emoji": "🍾", "color": "#eda100",
        "short": "Bottles and jars", "short_hi": "काँच की बोतलें और जार",
        "collectable": True, "donatable": False, "points_per_kg": 5, "partner_rate_per_kg": 2.0,
        "co2e_factor": 0.3, "sort_order": 4,
        "guidance": {
            "en": {
                "do": ["Rinse bottles and jars", "Wrap broken glass in newspaper and write \"SHARP\" on it"],
                "dont": ["Don't mix mirrors, window glass or crockery with bottles",
                         "Don't put bulbs or tube lights with glass"],
                "why": "Bottle glass melts cleanly into new bottles. Other glass types melt differently "
                       "and spoil the batch.",
            },
            "hi": {
                "do": ["बोतलें और जार धो लें", "टूटे काँच को अख़बार में लपेटकर \"SHARP / धारदार\" लिखें"],
                "dont": ["शीशा, खिड़की का काँच या क्रॉकरी बोतलों के साथ न मिलाएँ", "बल्ब या ट्यूबलाइट न डालें"],
                "why": "बोतल का काँच पिघलकर नई बोतल बनता है; दूसरे काँच इस प्रक्रिया को खराब करते हैं।",
            },
        },
    },
    {
        "slug": "textile", "name": "Textile", "name_hi": "कपड़ा", "emoji": "👕", "color": "#e87ba4",
        "short": "Clothes, shoes, bedsheets, fabric scraps", "short_hi": "कपड़े, जूते, चादरें, कतरन",
        "collectable": True, "donatable": True, "points_per_kg": 8, "partner_rate_per_kg": 3.0,
        "co2e_factor": 2.0, "sort_order": 5,
        "guidance": {
            "en": {
                "do": ["Donate clothes and shoes that can still be worn", "Wash and dry before giving",
                       "Tie shoes together in pairs"],
                "dont": ["Don't give wet or mouldy fabric", "Don't mix textiles with wet waste"],
                "why": "Wearable clothes help someone right away. Worn-out fabric can be shredded into "
                       "stuffing, rags or new yarn.",
            },
            "hi": {
                "do": ["पहनने लायक कपड़े और जूते दान करें", "देने से पहले धोकर सुखा लें", "जूतों को जोड़ी में बाँधें"],
                "dont": ["गीला या फफूंद लगा कपड़ा न दें", "कपड़ों को गीले कचरे में न मिलाएँ"],
                "why": "पहनने लायक कपड़े किसी के काम आते हैं; फटे कपड़ों से पोछे, भराई या नया धागा बनता है।",
            },
        },
    },
    {
        "slug": "ewaste", "name": "E-Waste", "name_hi": "ई-कचरा", "emoji": "🔋", "color": "#008300",
        "short": "Batteries, chargers, phones, electronic toys, bulbs",
        "short_hi": "बैटरी, चार्जर, फ़ोन, इलेक्ट्रॉनिक खिलौने, बल्ब",
        "collectable": True, "donatable": False, "points_per_kg": 20, "partner_rate_per_kg": 8.0,
        "co2e_factor": 1.5, "sort_order": 6,
        "guidance": {
            "en": {
                "do": ["Keep it separate and dry", "Tape the ends of loose batteries",
                       "Remove batteries from toys and remotes if it's easy",
                       "Delete personal data from phones and laptops"],
                "dont": ["Don't put it in the household bin", "Don't break it open or burn it",
                         "Don't store damaged or swollen batteries near heat"],
                "why": "Electronics can contain lead, mercury and lithium batteries that can harm people or "
                       "start fires. Authorised recyclers recover valuable metals safely.",
            },
            "hi": {
                "do": ["अलग और सूखा रखें", "खुली बैटरियों के सिरों पर टेप लगाएँ",
                       "आसानी से निकले तो खिलौने/रिमोट से बैटरी निकाल लें", "फ़ोन और लैपटॉप से निजी डेटा मिटाएँ"],
                "dont": ["घर के कूड़ेदान में न डालें", "तोड़ें या जलाएँ नहीं", "फूली हुई बैटरी गर्मी के पास न रखें"],
                "why": "इलेक्ट्रॉनिक्स में सीसा, पारा और लिथियम बैटरी हो सकती है जो नुकसान या आग का कारण बन सकती है।",
            },
        },
    },
    {
        "slug": "other", "name": "Other / Household", "name_hi": "अन्य / घरेलू", "emoji": "🗑️", "color": "#4a3aa7",
        "short": "Wet waste, sanitary, thermocol, medicines", "short_hi": "गीला कचरा, सैनिटरी, थर्माकोल, दवाइयाँ",
        "collectable": False, "donatable": False, "points_per_kg": 0, "partner_rate_per_kg": 0.0,
        "co2e_factor": 0.0, "sort_order": 7,
        "guidance": {
            "en": {
                "do": ["Compost kitchen waste or give it to the municipal wet-waste (green) bin",
                       "Wrap sanitary waste in paper and mark it", "Keep medicines, paint and chemicals separate"],
                "dont": ["Don't mix these with your dry recyclables", "Don't burn waste"],
                "why": "Swacchify collects clean dry waste only. These items spoil recyclables, so they "
                       "need your municipality's wet, sanitary or hazardous collection.",
            },
            "hi": {
                "do": ["रसोई का कचरा कम्पोस्ट करें या नगर निगम के हरे (गीले) डिब्बे में दें",
                       "सैनिटरी कचरा कागज़ में लपेटकर निशान लगाएँ", "दवाइयाँ, पेंट और केमिकल अलग रखें"],
                "dont": ["इन्हें सूखे रीसायकल कचरे में न मिलाएँ", "कचरा न जलाएँ"],
                "why": "स्वच्छिफ़ाई सिर्फ़ साफ़ सूखा कचरा लेता है। ये चीज़ें रीसायकल सामान को खराब करती हैं।",
            },
        },
    },
]

SUBCATEGORIES = {
    "plastic": [("pet", "PET bottles"), ("soft-plastic", "Soft plastic & packets"),
                ("hard-plastic", "Hard plastic"), ("multilayer", "Multi-layer packaging")],
    "paper": [("newspaper", "Newspaper & magazines"), ("cardboard", "Cardboard"), ("books", "Books & notebooks"),
              ("cartons", "Beverage cartons")],
    "metal": [("aluminium", "Aluminium"), ("steel-tin", "Steel & tin"), ("scrap-metal", "Scrap metal")],
    "glass": [("glass-containers", "Bottles & jars"), ("broken-glass", "Broken glass")],
    "textile": [("clothes", "Clothes"), ("footwear", "Footwear"), ("home-textiles", "Home textiles"),
                ("fabric-scraps", "Fabric scraps")],
    "ewaste": [("batteries", "Batteries"), ("chargers-cables", "Chargers & cables"),
               ("phones", "Mobile phones"), ("small-electronics", "Small electronics"),
               ("electronic-toys", "Electronic toys"), ("lamps", "CFL, LED & tube lights"),
               ("appliances", "Appliances")],
    "other": [("wet", "Wet / kitchen waste"), ("sanitary", "Sanitary waste"),
              ("hazardous", "Domestic hazardous"), ("non-recyclable", "Non-recyclable dry")],
}

LOCAL = "Rules differ by city. Check with your municipal corporation if unsure."


def _i(slug, name, name_hi, emoji, category, sub, aliases, do, why, dont, **kw):
    return {"slug": slug, "name": name, "name_hi": name_hi, "emoji": emoji, "category": category,
            "subcategory": sub, "aliases": aliases, "what_to_do": do, "why": why, "what_not_to_do": dont, **kw}


ITEMS = [
    # ── Plastic ────────────────────────────────────────────────────────────────────────────
    _i("plastic-bottle", "Plastic bottle", "प्लास्टिक की बोतल", "🧴", "plastic", "pet",
       ["plastic bottle", "water bottle", "pet bottle", "cold drink bottle", "soft drink bottle", "bisleri",
        "plastic botal", "प्लास्टिक बोतल", "पानी की बोतल"],
       "Empty it, squash it and put it with plastic.",
       "PET bottles are one of the most recycled plastics — they become new bottles, fibre and strapping.",
       "Don't leave liquid inside or stuff other waste into the bottle.",
       prep_tips="Caps can stay on after squashing.", lesson_slug="plastic-journey",
       related=["milk-packet", "glass-bottle"]),
    _i("milk-packet", "Milk packet", "दूध की थैली", "🥛", "plastic", "soft-plastic",
       ["milk packet", "milk pouch", "doodh ki thaili", "dudh packet", "curd packet", "dahi packet",
        "दूध की थैली", "दूध का पैकेट"],
       "Cut it fully open, rinse out the milk, dry it and put it with plastic.",
       "Milk pouches are good-quality plastic, but milk left inside turns sour and smells, which spoils other "
       "recyclables.",
       "Don't throw it away with milk still inside, and don't put it with wet waste.",
       prep_tips="Cut along one side fully so it dries flat.", lesson_slug="milk-packets",
       common_mistakes="Throwing the packet with a corner still full of milk."),
    _i("chips-packet", "Chips / snack wrapper", "चिप्स का पैकेट", "🍟", "plastic", "multilayer",
       ["chips packet", "chip packet", "snack wrapper", "biscuit wrapper", "namkeen packet", "kurkure",
        "maggi wrapper", "chocolate wrapper", "wrapper", "चिप्स पैकेट", "रैपर"],
       "Empty the crumbs and keep it with plastic, separate from wet waste.",
       "These shiny wrappers are multi-layer plastic (plastic + aluminium). They are hard to recycle, but kept "
       "clean they can go to brand take-back or co-processing instead of a landfill.",
       "Don't mix with wet waste and don't burn it.",
       local_note="Multi-layer packaging is accepted by some recyclers only. " + LOCAL),
    _i("plastic-bag", "Plastic carry bag", "प्लास्टिक की थैली", "🛍️", "plastic", "soft-plastic",
       ["plastic bag", "polythene", "polythene bag", "carry bag", "panni", "पन्नी", "पॉलिथीन", "प्लास्टिक थैली"],
       "Reuse it if you can. Otherwise stuff clean bags together into one bag and put them with plastic.",
       "Loose thin bags jam sorting machines; bundled together they are easier to handle.",
       "Don't use it to hold wet waste for recycling, and don't burn it.",
       reuse_tip="Carry a cloth bag so you get fewer plastic bags."),
    _i("food-container", "Plastic food container", "प्लास्टिक का डिब्बा", "🥡", "plastic", "hard-plastic",
       ["takeaway container", "food container", "tiffin box plastic", "plastic box", "plastic dabba",
        "ice cream tub", "curd cup", "plastic cup", "डिब्बा", "प्लास्टिक डब्बा"],
       "Scrape out food, rinse, dry and put with plastic.",
       "Hard plastic containers recycle well when clean.",
       "Don't put containers with gravy or oil still inside.", lesson_slug="plastic-journey"),
    _i("shampoo-bottle", "Shampoo / detergent bottle", "शैम्पू की बोतल", "🧼", "plastic", "hard-plastic",
       ["shampoo bottle", "detergent bottle", "cleaner bottle", "harpic bottle", "lotion bottle",
        "oil bottle", "शैम्पू बोतल"],
       "Empty it, rinse once and put with plastic.",
       "These are thick, valuable plastics that recyclers want.",
       "Don't include bottles still containing chemicals."),
    _i("plastic-toy", "Plastic toy (no battery)", "प्लास्टिक का खिलौना", "🧸", "plastic", "hard-plastic",
       ["plastic toy", "normal toy", "non electronic toy", "lego", "doll", "गुड़िया"],
       "If it still works, donate it. If broken, put it with hard plastic.",
       "Toys without electronics are usually hard plastic.",
       "Don't put toys with any wires, lights or batteries here — those are e-waste.",
       donatable=True, reuse_tip="Schools and anganwadis often welcome toys in good condition.",
       lesson_slug="donate-dont-dump"),
    _i("plastic-straw", "Straws & plastic cutlery", "स्ट्रॉ और प्लास्टिक चम्मच", "🥤", "plastic", "hard-plastic",
       ["straw", "plastic spoon", "plastic fork", "disposable cutlery", "plastic plate", "स्ट्रॉ", "चम्मच"],
       "Rinse and keep with plastic. Better still, avoid them.",
       "They are small and light, so they often escape sorting. Many single-use items like these are banned "
       "in India.",
       "Don't mix with food waste."),
    _i("hard-plastic-item", "Broken bucket / chair / mug", "टूटी बाल्टी / कुर्सी", "🪣", "plastic", "hard-plastic",
       ["bucket", "plastic chair", "mug", "plastic stool", "crate", "balti", "बाल्टी", "कुर्सी"],
       "Put with plastic. For big items, mention them in your pickup notes.",
       "Rigid plastic is shredded and recycled into new products.",
       "Don't leave metal parts or screws attached if you can remove them."),
    _i("bubble-wrap", "Bubble wrap / packing plastic", "बबल रैप", "📦", "plastic", "soft-plastic",
       ["bubble wrap", "packing plastic", "air pillow", "stretch film", "cling film", "cling wrap"],
       "Reuse it for packing, or keep it clean and put it with plastic.",
       "Clean film plastic can be recycled when collected in bulk.",
       "Don't include cling film that has food on it."),

    # ── Paper ──────────────────────────────────────────────────────────────────────────────
    _i("newspaper", "Newspaper & magazines", "अख़बार", "📰", "paper", "newspaper",
       ["newspaper", "news paper", "akhbar", "akhbaar", "raddi", "magazine", "pamphlet", "अख़बार", "अखबार",
        "रद्दी", "पत्रिका"],
       "Keep it dry, stack it and put it with paper.",
       "Newspaper is easy to recycle into new paper and cardboard.",
       "Don't include paper that is wet or has been used to wrap oily food."),
    _i("cardboard-box", "Cardboard box", "गत्ते का डिब्बा", "📦", "paper", "cardboard",
       ["cardboard", "carton box", "amazon box", "delivery box", "shoe box", "gatta", "गत्ता", "डिब्बा गत्ते का"],
       "Remove plastic tape if easy, flatten it and put with paper.",
       "Flat, dry cardboard is valuable and easy to recycle.",
       "Don't include wet or greasy cardboard.", lesson_slug="pizza-box"),
    _i("pizza-box", "Pizza box", "पिज़्ज़ा का डिब्बा", "🍕", "paper", "cardboard",
       ["pizza box", "pizza carton", "पिज़्ज़ा बॉक्स"],
       "Tear off the clean parts and put them with paper. The greasy, cheesy parts go to wet waste or "
       "compost.",
       "Oil soaks into the fibres and can't be washed out, so greasy cardboard spoils paper recycling.",
       "Don't put a whole greasy box with paper.", lesson_slug="pizza-box",
       common_mistakes="Recycling the entire box including the oily bottom."),
    _i("books", "Books", "किताबें", "📚", "paper", "books",
       ["book", "books", "textbook", "old books", "novel", "kitab", "kitaab", "किताब", "किताबें"],
       "If they're in good condition, donate them (choose \"Donate\" when you schedule a pickup). "
       "Otherwise put them with paper.",
       "A good book is worth more read again than recycled. Schools and libraries often need textbooks.",
       "Don't send wet or mouldy books for donation.", donatable=True, lesson_slug="donate-dont-dump",
       reuse_tip="Swacchify routes donated books to partner schools."),
    _i("notebook", "Notebooks & office paper", "कॉपी और कागज़", "📓", "paper", "books",
       ["notebook", "copy", "exam paper", "office paper", "printout", "a4 paper", "envelope", "कॉपी", "कागज"],
       "Remove spiral wire if easy, then put with paper.",
       "Writing paper is high-quality fibre and recycles well.",
       "Don't include carbon paper or laminated sheets.",
       reuse_tip="Unused pages can be torn out and reused as rough paper."),
    _i("paper-cup", "Paper cup / plate", "पेपर कप", "☕", "paper", "cartons",
       ["paper cup", "tea cup paper", "paper plate", "paper glass", "कागज़ का कप", "पेपर प्लेट"],
       "Rinse and keep it with paper, but separately from newspaper if you can.",
       "Most paper cups have a thin plastic lining, so only some recyclers accept them.",
       "Don't put cups with food or tea left inside.",
       local_note="Plastic-lined paper cups are accepted by some recyclers only. " + LOCAL),
    _i("beverage-carton", "Juice / milk carton (Tetra Pak)", "जूस का डिब्बा (टेट्रा पैक)", "🧃", "paper", "cartons",
       ["tetra pak", "tetrapak", "juice box", "juice carton", "milk carton", "frooti", "टेट्रा पैक", "जूस का डिब्बा"],
       "Empty it, flatten it and put with paper & cardboard.",
       "Cartons are paper with thin plastic and aluminium layers. Specialised recyclers separate them.",
       "Don't leave juice inside — it attracts insects."),
    _i("tissue-used", "Used tissue / napkin", "इस्तेमाल किया टिश्यू", "🧻", "other", "non-recyclable",
       ["tissue", "used tissue", "napkin", "paper napkin", "kitchen towel", "टिश्यू", "नैपकिन"],
       "Put it in wet waste or compost if it only has food or water. Tissues used for blowing your nose go "
       "with sanitary waste.",
       "Tissue fibres are too short to recycle, and used tissues are unhygienic to handle.",
       "Don't put used tissues with paper recycling."),
    _i("receipt", "Shop receipt (shiny paper)", "रसीद / बिल", "🧾", "other", "non-recyclable",
       ["receipt", "bill", "thermal paper", "atm slip", "रसीद", "बिल"],
       "Put it with non-recyclable dry waste.",
       "Shiny till receipts are thermal paper coated with chemicals, so they shouldn't be recycled with paper.",
       "Don't put them in paper recycling."),

    # ── Metal ──────────────────────────────────────────────────────────────────────────────
    _i("aluminium-can", "Aluminium can", "एल्युमिनियम कैन", "🥫", "metal", "aluminium",
       ["aluminium can", "aluminum can", "soda can", "beer can", "coke can", "drink can", "कैन"],
       "Empty it, give it a quick rinse and put with metal.",
       "Aluminium can be recycled endlessly, and recycling it uses far less energy than making new metal.",
       "Don't stuff other rubbish into the can.", lesson_slug="aluminium-cans"),
    _i("tin-can", "Food tin / can", "टिन का डिब्बा", "🥫", "metal", "steel-tin",
       ["tin", "tin can", "food can", "ghee tin", "oil tin", "biscuit tin", "टिन", "डब्बा टिन"],
       "Scrape out food, rinse, and put the lid inside the can. Put with metal.",
       "Steel tins are magnetic and easy to separate and recycle.",
       "Don't leave sharp lids loose — they can cut the collector.",
       safety_notes="Push sharp lids inside the tin."),
    _i("aluminium-foil", "Aluminium foil", "एल्युमिनियम फ़ॉयल", "🌯", "metal", "aluminium",
       ["foil", "aluminium foil", "silver foil", "roti foil", "फॉयल", "सिल्वर पन्नी"],
       "Wipe off food, scrunch it into a ball and put with metal.",
       "Clean foil is aluminium and recyclable; a ball is easier to sort than loose sheets.",
       "Don't include foil covered in food or oil."),
    _i("aerosol-can", "Spray can (deodorant, room freshener)", "स्प्रे कैन", "🧯", "metal", "aluminium",
       ["aerosol", "spray can", "deodorant", "deo", "room freshener", "hit spray", "स्प्रे"],
       "Only put it with metal when it is completely empty. Don't remove the nozzle.",
       "Spray cans are metal, but any gas left inside can burst under pressure.",
       "Don't pierce, crush or burn spray cans.", safety_notes="Keep away from heat and flames."),
    _i("utensils", "Old steel utensils / cookware", "पुराने बर्तन", "🍳", "metal", "scrap-metal",
       ["utensil", "steel utensil", "old vessels", "pressure cooker", "kadai", "pan", "tawa", "bartan",
        "बर्तन", "कुकर"],
       "Donate if usable. Otherwise put with metal. Remove plastic handles and rubber gaskets if easy.",
       "Steel and aluminium cookware is valuable scrap metal.",
       "Don't include non-stick coated pans with food residue."),
    _i("scrap-metal", "Nails, wire, small metal parts", "लोहे का कबाड़", "🔩", "metal", "scrap-metal",
       ["nails", "screws", "metal wire", "iron", "scrap", "kabad", "keys", "hanger metal", "कबाड़", "लोहा"],
       "Collect small pieces in a tin or box and put with metal.",
       "Loose small pieces get lost and can injure collectors.",
       "Don't include electrical wires with plugs — those are e-waste."),

    # ── Glass ──────────────────────────────────────────────────────────────────────────────
    _i("glass-bottle", "Glass bottle / jar", "काँच की बोतल / जार", "🍾", "glass", "glass-containers",
       ["glass bottle", "glass jar", "jam jar", "pickle jar", "sauce bottle", "beer bottle", "achar jar",
        "काँच की बोतल", "कांच", "जार"],
       "Empty it, rinse it and put with glass. Lids go with metal or plastic.",
       "Bottle glass can be melted into new bottles again and again.",
       "Don't mix it with mirrors, window glass or crockery.", lesson_slug="glass-safe"),
    _i("broken-glass", "Broken glass", "टूटा काँच", "🔪", "glass", "broken-glass",
       ["broken glass", "glass pieces", "broken bottle", "shattered glass", "टूटा कांच", "टूटा काँच"],
       "Wrap it in thick newspaper or put it in a box, write \"SHARP / धारदार\" on it, and put it with glass.",
       "Wrapped and labelled glass protects the person who collects it from cuts.",
       "Don't put loose broken glass in any bag.", safety_notes="Sweep carefully and never pick up small "
       "shards with bare hands.", lesson_slug="glass-safe"),
    _i("mirror-window-glass", "Mirror / window glass / crockery", "शीशा / क्रॉकरी", "🪞", "other", "non-recyclable",
       ["mirror", "window glass", "crockery", "ceramic", "cup broken", "plate broken", "porcelain",
        "शीशा", "आईना", "क्रॉकरी"],
       "Wrap it safely, label it \"SHARP\", and give it with non-recyclable dry waste or construction "
       "debris collection.",
       "Mirrors, window glass and ceramics melt at different temperatures from bottle glass and spoil its "
       "recycling.",
       "Don't mix these with glass bottles."),

    # ── Textile ────────────────────────────────────────────────────────────────────────────
    _i("old-clothes", "Old clothes", "पुराने कपड़े", "👕", "textile", "clothes",
       ["clothes", "old clothes", "shirt", "saree", "sari", "kurta", "jeans", "t-shirt", "kapde", "kapda",
        "कपड़े", "पुराने कपड़े", "साड़ी"],
       "If they can still be worn, wash them and choose \"Donate\" in your pickup. Torn clothes go with "
       "textile recycling.",
       "Wearable clothes help another family. Worn-out ones become rags, stuffing or new yarn.",
       "Don't give wet, dirty or mouldy clothes.", donatable=True, lesson_slug="old-clothes"),
    _i("shoes", "Shoes & slippers", "जूते और चप्पल", "👟", "textile", "footwear",
       ["shoes", "shoe", "slippers", "chappal", "sandals", "sneakers", "joote", "jootey", "जूते", "चप्पल"],
       "Donate wearable pairs. Worn-out shoes go with textile — tie each pair together.",
       "Shoe-recycling programmes can refurbish soles into new footwear for children.",
       "Don't send single, unpaired shoes for donation.", donatable=True,
       reuse_tip="Some organisations refurbish old sneakers into new footwear for children."),
    _i("bedsheet-towel", "Bedsheets, towels, curtains", "चादर, तौलिया, पर्दे", "🛏️", "textile", "home-textiles",
       ["bedsheet", "towel", "curtain", "blanket", "pillow cover", "chadar", "tauliya", "चादर", "तौलिया",
        "कंबल", "पर्दा"],
       "Donate if usable (animal shelters often need old blankets). Otherwise put with textile.",
       "Home textiles are good-quality fabric for reuse or recycling.",
       "Don't give wet or mouldy fabric.", donatable=True),
    _i("fabric-scraps", "Tailoring scraps / clean fabric waste", "कपड़े की कतरन", "🧵", "textile", "fabric-scraps",
       ["fabric waste", "cloth scraps", "katran", "tailor waste", "cutting waste", "boutique waste",
        "कतरन", "कपड़े के टुकड़े"],
       "Collect clean scraps in a bag and put with textile. Shops can schedule regular pickups.",
       "Clean scraps are shredded into fibre for new yarn, stuffing or industrial wipes.",
       "Don't mix scraps with thread cones, pins or plastic."),
    _i("bags-backpacks", "Bags & backpacks", "बैग और बस्ते", "🎒", "textile", "clothes",
       ["bag", "backpack", "school bag", "handbag", "basta", "बस्ता", "बैग"],
       "Donate usable school bags. Otherwise put with textile.",
       "School bags in good condition are very useful for children.", "Don't leave things inside.",
       donatable=True),
    _i("mattress-pillow", "Mattress / pillow", "गद्दा / तकिया", "🛌", "other", "non-recyclable",
       ["mattress", "pillow", "gadda", "takiya", "cushion", "गद्दा", "तकिया"],
       "These are bulky. Contact your municipal bulky-waste service or a local mattress recycler.",
       "Foam and coir mattresses need special handling and don't fit in normal collection.",
       "Don't dump them on the roadside.", local_note=LOCAL),

    # ── E-waste ────────────────────────────────────────────────────────────────────────────
    _i("batteries", "Batteries (AA, AAA, cells)", "बैटरी / सेल", "🔋", "ewaste", "batteries",
       ["battery", "batteries", "cell", "cells", "aa battery", "aaa battery", "pencil cell", "button cell",
        "watch battery", "बैटरी", "सेल"],
       "Keep used batteries in a small box, tape the ends and give them as e-waste.",
       "Batteries contain metals and chemicals that can leak, and some can spark or catch fire in a "
       "garbage truck.",
       "Don't put batteries in the household bin or with metal.", safety_notes="Store in a cool, dry place.",
       lesson_slug="batteries", common_mistakes="Throwing cells in the dustbin with other waste."),
    _i("power-bank", "Power bank / lithium battery", "पावर बैंक", "🔋", "ewaste", "batteries",
       ["power bank", "powerbank", "lithium battery", "li-ion", "phone battery", "laptop battery",
        "swollen battery", "पावर बैंक"],
       "Tape the ports, keep it away from heat and give it as e-waste. Mention it in your pickup notes.",
       "Lithium batteries can catch fire if crushed or punctured.",
       "Don't puncture, crush or charge a swollen battery.",
       safety_notes="If a battery is swollen or hot, keep it in a metal tin or on sand, away from anything "
       "that can burn.", lesson_slug="batteries"),
    _i("mobile-phone", "Mobile phone / tablet", "मोबाइल फ़ोन", "📱", "ewaste", "phones",
       ["phone", "mobile", "mobile phone", "smartphone", "old phone", "damaged phone", "broken phone",
        "tablet", "ipad", "फ़ोन", "मोबाइल"],
       "Back up and factory-reset it, remove the SIM and memory card, then give it as e-waste.",
       "Phones contain gold, copper and a lithium battery. Authorised recyclers recover them safely.",
       "Don't sell it to informal burners or break it open.",
       safety_notes="A cracked or swollen phone battery is a fire risk.", lesson_slug="ewaste-why"),
    _i("charger-cable", "Charger / cable / earphones", "चार्जर / तार / ईयरफ़ोन", "🔌", "ewaste", "chargers-cables",
       ["charger", "cable", "wire", "usb cable", "earphones", "headphones", "adapter", "extension board",
        "चार्जर", "तार", "ईयरफोन"],
       "Bundle cables with a rubber band and give them as e-waste.",
       "Cables contain copper; chargers contain circuit boards.",
       "Don't burn wires to get the copper out — the smoke is toxic.", lesson_slug="ewaste-why"),
    _i("small-electronics", "Small electronics (remote, calculator, mouse)", "छोटे इलेक्ट्रॉनिक्स", "🖱️", "ewaste",
       "small-electronics",
       ["remote", "tv remote", "calculator", "mouse", "keyboard", "router", "modem", "set top box",
        "trimmer", "hair dryer", "digital watch", "रिमोट"],
       "Remove batteries if easy (they go in the battery box) and give it as e-waste.",
       "Anything with a circuit board, plug or battery is e-waste.",
       "Don't put it in plastic recycling just because the outside is plastic."),
    _i("laptop-computer", "Laptop / computer / monitor", "लैपटॉप / कंप्यूटर", "💻", "ewaste", "small-electronics",
       ["laptop", "computer", "desktop", "monitor", "cpu", "printer", "hard disk", "लैपटॉप", "कंप्यूटर"],
       "Back up and wipe your data, then give it as e-waste.",
       "Computers contain valuable metals and some hazardous parts.",
       "Don't dismantle it yourself.", lesson_slug="ewaste-why"),
    _i("electronic-toy", "Electronic / robot toy", "इलेक्ट्रॉनिक खिलौना", "🤖", "ewaste", "electronic-toys",
       ["robot toy", "electronic toy", "battery toy", "remote control car", "rc car", "toy with battery",
        "musical toy", "light up toy", "talking toy", "robot", "रोबोट खिलौना", "बैटरी वाला खिलौना"],
       "If it still works, consider donating it. Otherwise remove the batteries if easy and give the toy as "
       "e-waste.",
       "It contains electronic parts and often a battery, so it shouldn't go with ordinary plastic.",
       "Don't put it with regular plastic or household waste.", donatable=True, lesson_slug="ewaste-why"),
    _i("cfl-bulb", "CFL / tube light", "सीएफ़एल / ट्यूबलाइट", "💡", "ewaste", "lamps",
       ["cfl", "cfl bulb", "tube light", "tubelight", "fluorescent", "energy saver bulb", "सीएफएल", "ट्यूबलाइट"],
       "Keep it unbroken in its box or wrapped in paper, and give it as e-waste.",
       "CFLs and tube lights contain a small amount of mercury, which is released if they break.",
       "Don't break it or put it with glass or household waste.",
       safety_notes="If one breaks: open windows, leave the room for 15 minutes, then sweep pieces with stiff "
       "paper (not a vacuum) into a sealed bag."),
    _i("led-bulb", "LED bulb", "एलईडी बल्ब", "💡", "ewaste", "lamps",
       ["led", "led bulb", "led light", "led batten", "एलईडी"],
       "Give it as e-waste.", "LED bulbs contain a small circuit board.",
       "Don't put it with glass."),
    _i("incandescent-bulb", "Old filament bulb", "पुराना पीला बल्ब", "💡", "other", "non-recyclable",
       ["filament bulb", "incandescent bulb", "yellow bulb", "normal bulb", "पीला बल्ब"],
       "Wrap it and put with non-recyclable dry waste.",
       "Old filament bulbs are mixed glass and metal that normal glass recyclers don't take.",
       "Don't put it with glass bottles."),
    _i("appliance", "Appliances (mixer, iron, fan, TV)", "उपकरण (मिक्सर, प्रेस, पंखा)", "🔌", "ewaste", "appliances",
       ["mixer", "grinder", "iron", "press", "fan", "tv", "television", "microwave", "kettle", "toaster",
        "fridge", "washing machine", "ac", "मिक्सर", "प्रेस", "पंखा", "टीवी"],
       "Give it as e-waste. For big appliances (fridge, washing machine, AC) mention the size in your pickup "
       "notes. Many brands also run take-back programmes.",
       "Appliances contain metals, circuit boards and sometimes refrigerant gases that need proper handling.",
       "Don't break it for parts or dump it.", local_note="Large appliances may need a separate appointment."),
    _i("ink-cartridge", "Printer cartridge / toner", "प्रिंटर कार्ट्रिज", "🖨️", "ewaste", "small-electronics",
       ["cartridge", "ink cartridge", "toner", "printer ink"],
       "Seal it in a bag and give it as e-waste, or return it to the brand if they offer take-back.",
       "Cartridges contain ink residue and electronic chips.", "Don't put it with plastic."),

    # ── Other / household ──────────────────────────────────────────────────────────────────
    _i("food-waste", "Food & kitchen waste", "रसोई का गीला कचरा", "🥬", "other", "wet",
       ["food waste", "kitchen waste", "vegetable peels", "fruit peels", "leftover food", "tea leaves",
        "egg shells", "wet waste", "geela kachra", "coconut shell", "nariyal", "puja flowers", "flowers",
        "garden waste", "leaves", "गीला कचरा", "छिलके", "बचा खाना", "नारियल", "फूल"],
       "Compost it at home or put it in your municipality's wet-waste (green) bin.",
       "Wet waste rots and smells, and makes dry recyclables dirty. As compost, it becomes good soil.",
       "Don't mix it with dry waste or put it in plastic bags inside the recycling.",
       local_note="Swacchify doesn't collect wet waste."),
    _i("wet-wipes", "Wet wipes / wet tissues", "वेट वाइप्स", "🧻", "other", "sanitary",
       ["wet wipes", "wet tissue", "wet tissues", "baby wipes", "wipes", "वेट टिश्यू", "वाइप्स"],
       "Put used wipes with sanitary waste. Please don't flush them.",
       "Wet wipes contain plastic fibres, so they don't break down and can't be recycled. They also block "
       "drains.",
       "Don't flush them or put them with paper.",
       reuse_tip="A washable cloth works for most jobs wipes are used for.", lesson_slug="what-we-dont-take"),
    _i("thermocol", "Thermocol", "थर्माकोल", "⬜", "other", "non-recyclable",
       ["thermocol", "styrofoam", "polystyrene", "eps", "foam packaging", "thermocol plate",
        "thermocol glass", "थर्माकोल"],
       "Reuse packing thermocol if you can. Otherwise keep it clean, break it into smaller pieces and give it "
       "to municipal dry-waste collection.",
       "Thermocol is almost all air, so it is costly to transport and very few recyclers accept it. "
       "Swacchify doesn't collect it.",
       "Don't burn it — the smoke is toxic. Avoid thermocol plates and cups.",
       local_note="Some cities have special thermocol collection. " + LOCAL, lesson_slug="what-we-dont-take"),
    _i("sanitary-waste", "Sanitary pads / diapers", "सैनिटरी पैड / डायपर", "🩹", "other", "sanitary",
       ["sanitary pad", "pad", "diaper", "nappy", "tampon", "sanitary napkin", "सैनिटरी पैड", "डायपर"],
       "Wrap it in newspaper, mark it with a red dot, and give it to the sanitary-waste collection.",
       "Sanitary waste is a health risk for collectors if it's mixed with other waste.",
       "Don't flush it or mix it with dry or wet waste."),
    _i("medicines", "Expired medicines", "एक्सपायर दवाइयाँ", "💊", "other", "hazardous",
       ["medicine", "medicines", "tablets", "expired medicine", "syrup", "dawai", "dawa", "दवाई", "दवाइयाँ"],
       "Keep them in their packs and give them to a pharmacy take-back or the municipal hazardous-waste "
       "collection where available.",
       "Medicines can pollute water and soil, and can be dangerous if someone else takes them.",
       "Don't flush them or throw them in the open.", local_note=LOCAL),
    _i("sharps", "Needles, syringes, lancets", "सुई / सिरिंज", "💉", "other", "hazardous",
       ["syringe", "needle", "insulin needle", "lancet", "injection", "सिरिंज", "सुई"],
       "Put them in a hard plastic bottle with a lid, label it \"SHARPS\" and give it to a hospital, clinic or "
       "the hazardous-waste collection.",
       "Loose needles can injure and infect collectors.",
       "Never put loose needles in any bin."),
    _i("paint-chemicals", "Paint, chemicals, pesticide cans", "पेंट और केमिकल", "🎨", "other", "hazardous",
       ["paint", "paint can", "chemical", "pesticide", "thinner", "acid", "phenyl", "पेंट", "केमिकल"],
       "Keep them closed in their original container and give them to the domestic hazardous-waste "
       "collection.",
       "Chemicals can burn, poison or react with other waste.",
       "Don't pour them down the drain or mix them with other waste.", local_note=LOCAL),
    _i("cigarette-butts", "Cigarette butts", "सिगरेट के टुकड़े", "🚬", "other", "non-recyclable",
       ["cigarette", "cigarette butt", "bidi", "ash"],
       "Make sure they're fully out, then put them with non-recyclable dry waste.",
       "Filters are plastic fibres full of toxins, so they can't be recycled.",
       "Don't throw them on the ground or in drains."),
    _i("wooden-items", "Wood (toys, small furniture)", "लकड़ी का सामान", "🪵", "other", "non-recyclable",
       ["wood", "wooden", "wooden toy", "furniture", "plywood", "लकड़ी"],
       "Donate if usable. Untreated wood can go to a carpenter or scrap dealer; bigger furniture needs your "
       "municipality's bulky-waste service.",
       "Clean wood can be reused, but painted or laminated wood needs special handling.",
       "Don't burn painted or laminated wood.", donatable=True, local_note=LOCAL),
    _i("rubber-tyre", "Rubber / tyres", "रबर / टायर", "🛞", "other", "non-recyclable",
       ["tyre", "tire", "rubber", "tube", "rubber band", "टायर", "रबर"],
       "Return tyres to a tyre shop. Small rubber items go with non-recyclable dry waste.",
       "Tyre shops send old tyres to authorised recyclers.",
       "Don't burn tyres."),

    # ── Ambiguous parents (ask first) ──────────────────────────────────────────────────────
    _i("toy", "Toy", "खिलौना", "🧸", "plastic", "hard-plastic",
       ["toy", "toys", "khilona", "khilone", "खिलौना", "खिलौने"],
       "It depends on the toy.", "Toys are made of very different materials.", "Don't guess — pick the type.",
       clarify={
           "question": "What kind of toy is it?", "question_hi": "यह किस तरह का खिलौना है?",
           "options": [
               {"label": "Normal toy", "label_hi": "सामान्य खिलौना", "emoji": "🧸", "item": "plastic-toy"},
               {"label": "Electronic / robot toy", "label_hi": "इलेक्ट्रॉनिक / रोबोट", "emoji": "🤖",
                "item": "electronic-toy"},
               {"label": "Battery-powered toy", "label_hi": "बैटरी वाला खिलौना", "emoji": "🔋",
                "item": "electronic-toy"},
               {"label": "Wooden toy", "label_hi": "लकड़ी का खिलौना", "emoji": "🪵", "item": "wooden-items"},
               {"label": "Soft / cloth toy", "label_hi": "कपड़े का खिलौना", "emoji": "🧶", "item": "old-clothes"},
           ],
       }),
    _i("bulb", "Bulb / light", "बल्ब", "💡", "ewaste", "lamps",
       ["bulb", "light bulb", "light", "बल्ब"],
       "It depends on the bulb.", "Different bulbs contain different materials.", "Don't put any bulb with glass.",
       clarify={
           "question": "Which kind of bulb is it?", "question_hi": "यह कौन-सा बल्ब है?",
           "options": [
               {"label": "CFL (spiral) / tube light", "label_hi": "सीएफ़एल / ट्यूबलाइट", "emoji": "🌀",
                "item": "cfl-bulb"},
               {"label": "LED bulb", "label_hi": "एलईडी बल्ब", "emoji": "💡", "item": "led-bulb"},
               {"label": "Old yellow filament bulb", "label_hi": "पुराना पीला बल्ब", "emoji": "🟡",
                "item": "incandescent-bulb"},
           ],
       }),
    _i("bottle", "Bottle", "बोतल", "🍶", "plastic", "pet",
       ["bottle", "bottles", "botal", "बोतल"],
       "It depends on the bottle.", "Bottles are made of plastic or glass.", "Don't guess — pick the type.",
       clarify={
           "question": "What is the bottle made of?", "question_hi": "बोतल किस चीज़ की है?",
           "options": [
               {"label": "Plastic bottle", "label_hi": "प्लास्टिक", "emoji": "🧴", "item": "plastic-bottle"},
               {"label": "Glass bottle", "label_hi": "काँच", "emoji": "🍾", "item": "glass-bottle"},
               {"label": "Shampoo / cleaner bottle", "label_hi": "शैम्पू / क्लीनर", "emoji": "🧼",
                "item": "shampoo-bottle"},
               {"label": "Medicine bottle", "label_hi": "दवाई की बोतल", "emoji": "💊", "item": "medicines"},
           ],
       }),
    _i("packet", "Packet / wrapper", "पैकेट", "🛍️", "plastic", "soft-plastic",
       ["packet", "packets", "pouch", "पैकेट"],
       "It depends on the packet.", "Packets are made of different layers.", "Don't guess — pick the type.",
       clarify={
           "question": "What kind of packet?", "question_hi": "कैसा पैकेट है?",
           "options": [
               {"label": "Milk / curd packet", "label_hi": "दूध / दही की थैली", "emoji": "🥛",
                "item": "milk-packet"},
               {"label": "Chips / snack wrapper (shiny)", "label_hi": "चिप्स / नमकीन (चमकीला)", "emoji": "🍟",
                "item": "chips-packet"},
               {"label": "Carry bag / polythene", "label_hi": "पॉलिथीन", "emoji": "🛍️", "item": "plastic-bag"},
               {"label": "Juice / milk carton", "label_hi": "जूस का डिब्बा", "emoji": "🧃",
                "item": "beverage-carton"},
           ],
       }),
    _i("box", "Box", "डिब्बा", "📦", "paper", "cardboard",
       ["box", "boxes", "dabba", "डिब्बा"],
       "It depends on the box.", "Boxes are made of different materials.", "Don't guess — pick the type.",
       clarify={
           "question": "What is the box made of?", "question_hi": "डिब्बा किस चीज़ का है?",
           "options": [
               {"label": "Cardboard box", "label_hi": "गत्ता", "emoji": "📦", "item": "cardboard-box"},
               {"label": "Pizza box", "label_hi": "पिज़्ज़ा बॉक्स", "emoji": "🍕", "item": "pizza-box"},
               {"label": "Plastic box", "label_hi": "प्लास्टिक डिब्बा", "emoji": "🥡", "item": "food-container"},
               {"label": "Thermocol box", "label_hi": "थर्माकोल", "emoji": "⬜", "item": "thermocol"},
               {"label": "Metal tin", "label_hi": "टिन", "emoji": "🥫", "item": "tin-can"},
           ],
       }),
    _i("cup", "Cup", "कप", "☕", "paper", "cartons",
       ["cup", "glass cup", "कप", "गिलास"],
       "It depends on the cup.", "Cups are made of different materials.", "Don't guess — pick the type.",
       clarify={
           "question": "What is the cup made of?", "question_hi": "कप किस चीज़ का है?",
           "options": [
               {"label": "Paper cup", "label_hi": "कागज़ का कप", "emoji": "☕", "item": "paper-cup"},
               {"label": "Plastic cup", "label_hi": "प्लास्टिक कप", "emoji": "🥤", "item": "food-container"},
               {"label": "Thermocol cup", "label_hi": "थर्माकोल कप", "emoji": "⬜", "item": "thermocol"},
               {"label": "Ceramic / broken mug", "label_hi": "चीनी मिट्टी", "emoji": "🍵",
                "item": "mirror-window-glass"},
           ],
       }),
]

DROPOFF_POINTS = [
    {"name": "Swacchify Hub — Malviya Nagar", "kind": "swacchify_hub",
     "accepted_categories": ["plastic", "paper", "metal", "glass", "textile", "ewaste"],
     "address": "Sector 4, Malviya Nagar", "city": "Jaipur", "lat": 26.8539, "lng": 75.8049,
     "hours": "Mon–Sat, 9 am – 6 pm"},
    {"name": "Swacchify Hub — Vaishali Nagar", "kind": "swacchify_hub",
     "accepted_categories": ["plastic", "paper", "metal", "glass", "textile", "ewaste"],
     "address": "Amrapali Marg, Vaishali Nagar", "city": "Jaipur", "lat": 26.9110, "lng": 75.7430,
     "hours": "Mon–Sat, 9 am – 6 pm"},
    {"name": "E-waste drop box — C-Scheme", "kind": "ewaste_bin", "accepted_categories": ["ewaste"],
     "address": "Near Ashok Marg, C-Scheme", "city": "Jaipur", "lat": 26.9056, "lng": 75.8030,
     "hours": "Open 24 hours"},
    {"name": "E-waste drop box — Mansarovar", "kind": "ewaste_bin", "accepted_categories": ["ewaste"],
     "address": "Madhyam Marg, Mansarovar", "city": "Jaipur", "lat": 26.8710, "lng": 75.7570,
     "hours": "Open 24 hours"},
    {"name": "Books & clothes donation box — Raja Park", "kind": "donation_box",
     "accepted_categories": ["paper", "textile"], "address": "Community Centre, Raja Park",
     "city": "Jaipur", "lat": 26.8990, "lng": 75.8270, "hours": "Daily, 8 am – 8 pm"},
    {"name": "School donation desk — Bani Park", "kind": "donation_box", "accepted_categories": ["paper", "textile"],
     "address": "Near Collectorate Circle, Bani Park", "city": "Jaipur", "lat": 26.9280, "lng": 75.7950,
     "hours": "Mon–Fri, 10 am – 4 pm"},
    {"name": "Dry-waste recycling centre — Jhotwara", "kind": "recycling_center",
     "accepted_categories": ["plastic", "paper", "metal", "glass"], "address": "Industrial Area, Jhotwara",
     "city": "Jaipur", "lat": 26.9460, "lng": 75.7390, "hours": "Mon–Sat, 8 am – 5 pm"},
]
