"""Micro-lessons (one practical idea each, 20–90 s), quizzes, daily tips/challenges and reward catalogue."""


def s(emoji, text, text_hi):
    return {"emoji": emoji, "text": text, "text_hi": text_hi}


def q(question, question_hi, options, correct, explanation, explanation_hi):
    return {"question": question, "question_hi": question_hi,
            "options": [{"text": o[0], "text_hi": o[1]} for o in options],
            "correct_index": correct, "explanation": explanation, "explanation_hi": explanation_hi}


LESSONS = [
    {
        "slug": "three-bins", "category_slug": "general", "emoji": "🗂️", "duration_sec": 45,
        "title": "Segregation in 45 seconds", "title_hi": "45 सेकंड में कचरा अलग करना",
        "description": "The three groups every home needs: wet, dry and hazardous.",
        "description_hi": "हर घर के लिए तीन हिस्से: गीला, सूखा और हानिकारक।",
        "slides": [
            s("🥬", "Wet waste is anything that rots: peels, leftover food, tea leaves.",
              "गीला कचरा वह है जो सड़ता है: छिलके, बचा खाना, चायपत्ती।"),
            s("📦", "Dry waste is plastic, paper, metal, glass and cloth. Keep it clean and dry.",
              "सूखा कचरा है प्लास्टिक, कागज़, धातु, काँच और कपड़ा। इसे साफ़ और सूखा रखें।"),
            s("⚠️", "Hazardous waste is batteries, medicines, bulbs, paint and sharp things. Keep it separate.",
              "हानिकारक कचरा है बैटरी, दवाइयाँ, बल्ब, पेंट और धारदार चीज़ें। इन्हें अलग रखें।"),
            s("✅", "Two bins and one small box is all you need to start.",
              "शुरू करने के लिए दो डिब्बे और एक छोटा बॉक्स काफ़ी है।"),
        ],
        "quiz": [
            q("Where do vegetable peels go?", "सब्ज़ी के छिलके कहाँ जाएँगे?",
              [("Dry waste", "सूखा कचरा"), ("Wet waste", "गीला कचरा"), ("E-waste", "ई-कचरा"),
               ("Textile", "कपड़ा")], 1,
              "Peels rot, so they are wet waste — perfect for compost.",
              "छिलके सड़ते हैं, इसलिए ये गीला कचरा हैं — कम्पोस्ट के लिए बढ़िया।"),
            q("Which of these is hazardous?", "इनमें से हानिकारक क्या है?",
              [("Newspaper", "अख़बार"), ("Plastic bottle", "प्लास्टिक बोतल"), ("Used battery", "पुरानी बैटरी"),
               ("Old shirt", "पुरानी शर्ट")], 2,
              "Batteries contain chemicals and must be kept separate.",
              "बैटरी में केमिकल होते हैं, इसलिए इसे अलग रखें।"),
        ],
    },
    {
        "slug": "batteries", "category_slug": "ewaste", "emoji": "🔋", "duration_sec": 45,
        "title": "How to handle used batteries", "title_hi": "पुरानी बैटरियों का क्या करें",
        "description": "Why batteries never go in the dustbin, and a simple way to store them.",
        "description_hi": "बैटरी कूड़ेदान में क्यों नहीं जाती, और उसे कैसे रखें।",
        "slides": [
            s("🔋", "Used batteries still hold chemicals and a little energy.",
              "पुरानी बैटरी में अब भी केमिकल और थोड़ी ऊर्जा होती है।"),
            s("🔥", "Crushed in a garbage truck, some batteries can spark or catch fire.",
              "कचरा गाड़ी में दबने पर कुछ बैटरियाँ चिंगारी या आग पकड़ सकती हैं।"),
            s("📦", "Keep a small 'battery box' at home. Tape the ends of each battery.",
              "घर में एक छोटा 'बैटरी बॉक्स' रखें। हर बैटरी के सिरों पर टेप लगाएँ।"),
            s("🚚", "When the box is full, schedule an e-waste pickup.",
              "बॉक्स भर जाए तो ई-कचरा पिकअप बुक करें।"),
        ],
        "quiz": [
            q("Where should used batteries go?", "पुरानी बैटरी कहाँ जानी चाहिए?",
              [("Normal waste", "सामान्य कचरा"), ("Battery / e-waste collection", "बैटरी / ई-कचरा संग्रह"),
               ("Paper bin", "कागज़ का डिब्बा"), ("Textile bin", "कपड़े का डिब्बा")], 1,
              "Batteries are e-waste. Keep them separate and give them to e-waste collection.",
              "बैटरी ई-कचरा है। इसे अलग रखें और ई-कचरा संग्रह में दें।"),
            q("What should you do before storing a loose battery?", "खुली बैटरी रखने से पहले क्या करें?",
              [("Wet it", "गीला करें"), ("Tape the ends", "सिरों पर टेप लगाएँ"), ("Break it", "तोड़ दें"),
               ("Heat it", "गरम करें")], 1,
              "Taping the ends stops batteries touching and sparking.",
              "टेप लगाने से बैटरियाँ आपस में छूकर चिंगारी नहीं करतीं।"),
        ],
    },
    {
        "slug": "ewaste-why", "category_slug": "ewaste", "emoji": "🤖", "duration_sec": 60,
        "title": "Is it e-waste? The plug-and-battery rule", "title_hi": "क्या यह ई-कचरा है? प्लग-और-बैटरी नियम",
        "description": "A one-line rule to spot e-waste: toys, chargers, remotes and more.",
        "description_hi": "ई-कचरा पहचानने का आसान नियम: खिलौने, चार्जर, रिमोट और भी।",
        "slides": [
            s("🔌", "Simple rule: if it has a plug, a battery, or lights up — it's e-waste.",
              "आसान नियम: जिसमें प्लग हो, बैटरी हो, या जो जलता हो — वह ई-कचरा है।"),
            s("🤖", "That includes robot toys, musical cards, remotes, earphones and chargers.",
              "इसमें रोबोट खिलौने, म्यूज़िकल कार्ड, रिमोट, ईयरफ़ोन और चार्जर शामिल हैं।"),
            s("🪙", "E-waste contains gold, copper and other metals that can be recovered.",
              "ई-कचरे में सोना, ताँबा और दूसरी धातुएँ होती हैं जो वापस निकाली जा सकती हैं।"),
            s("☠️", "Burning wires or breaking circuit boards releases toxic smoke. Leave it to authorised recyclers.",
              "तार जलाने या सर्किट तोड़ने से ज़हरीला धुआँ निकलता है। इसे अधिकृत रीसायकलर पर छोड़ें।"),
        ],
        "quiz": [
            q("What category does an old electronic toy generally belong to?",
              "पुराना इलेक्ट्रॉनिक खिलौना आमतौर पर किस श्रेणी में आता है?",
              [("Plastic", "प्लास्टिक"), ("E-waste", "ई-कचरा"), ("Wet waste", "गीला कचरा"), ("Paper", "कागज़")], 1,
              "It has electronics and usually a battery, so it's e-waste.",
              "इसमें इलेक्ट्रॉनिक्स और अक्सर बैटरी होती है, इसलिए यह ई-कचरा है।"),
            q("Is an old phone charger e-waste?", "क्या पुराना फ़ोन चार्जर ई-कचरा है?",
              [("Yes", "हाँ"), ("No, it's plastic", "नहीं, यह प्लास्टिक है")], 0,
              "Chargers contain a circuit board and copper — they're e-waste.",
              "चार्जर में सर्किट और ताँबा होता है — यह ई-कचरा है।"),
        ],
    },
    {
        "slug": "plastic-journey", "category_slug": "plastic", "emoji": "🧴", "duration_sec": 60,
        "title": "What happens after plastic is collected?", "title_hi": "प्लास्टिक इकट्ठा होने के बाद क्या होता है?",
        "description": "Follow a bottle from your home to a recycling plant.",
        "description_hi": "एक बोतल का सफ़र — आपके घर से रीसायकलिंग प्लांट तक।",
        "slides": [
            s("🏠", "It starts at home: an empty, dry bottle kept apart from wet waste.",
              "शुरुआत घर से: खाली, सूखी बोतल जो गीले कचरे से अलग रखी गई।"),
            s("🚚", "A collection partner picks it up and weighs it at the hub.",
              "संग्रह साथी इसे उठाते हैं और हब पर तौलते हैं।"),
            s("🧺", "At the recycler, plastics are sorted by type, washed and shredded into flakes.",
              "रीसायकलर पर प्लास्टिक को प्रकार के हिसाब से छाँटा, धोया और टुकड़ों में काटा जाता है।"),
            s("🧵", "Flakes become new bottles, polyester fibre, straps and more.",
              "इन टुकड़ों से नई बोतलें, पॉलिएस्टर धागा, पट्टियाँ और बहुत कुछ बनता है।"),
            s("🍛", "Food left inside ruins this chain. Clean and dry is the key.",
              "अंदर बचा खाना यह पूरी प्रक्रिया बिगाड़ देता है। साफ़ और सूखा — यही मंत्र है।"),
        ],
        "quiz": [
            q("What most often stops plastic from being recycled?", "प्लास्टिक रीसायकल न होने की सबसे बड़ी वजह क्या है?",
              [("Its colour", "उसका रंग"), ("Food and liquid left inside", "अंदर बचा खाना और तरल"),
               ("Its size", "उसका आकार"), ("The brand", "ब्रांड")], 1,
              "Dirty plastic contaminates the batch. Empty, rinse and dry it.",
              "गंदा प्लास्टिक पूरे बैच को खराब करता है। खाली करें, धोएँ, सुखाएँ।"),
        ],
    },
    {
        "slug": "milk-packets", "category_slug": "plastic", "emoji": "🥛", "duration_sec": 30,
        "title": "The 10-second milk packet habit", "title_hi": "दूध की थैली की 10 सेकंड वाली आदत",
        "description": "Cut, rinse, dry — and your milk packets become recyclable.",
        "description_hi": "काटें, धोएँ, सुखाएँ — और आपकी दूध की थैली रीसायकल हो जाएगी।",
        "slides": [
            s("✂️", "Cut the packet fully open along one side.", "थैली को एक तरफ़ से पूरा काटें।"),
            s("🚿", "Rinse once so no milk is left.", "एक बार धो लें ताकि दूध न बचे।"),
            s("☀️", "Dry it flat and stack with plastic.", "चपटा सुखाकर प्लास्टिक के साथ रखें।"),
        ],
        "quiz": [
            q("Can you put a milk packet with plastic?", "क्या दूध की थैली प्लास्टिक के साथ रख सकते हैं?",
              [("Yes, straight from the fridge", "हाँ, सीधे फ्रिज से"), ("Yes, after rinsing and drying",
               "हाँ, धोकर और सुखाकर"), ("No, never", "नहीं, कभी नहीं")], 1,
              "Rinsed and dry milk packets are good-quality recyclable plastic.",
              "धुली और सूखी दूध की थैली अच्छा रीसायकल प्लास्टिक है।"),
        ],
    },
    {
        "slug": "pizza-box", "category_slug": "paper", "emoji": "🍕", "duration_sec": 30,
        "title": "Can greasy pizza boxes be recycled?", "title_hi": "क्या तेल वाला पिज़्ज़ा बॉक्स रीसायकल होता है?",
        "description": "Tear, sort, done: the clean-lid trick.", "description_hi": "फाड़ें, छाँटें — साफ़ ढक्कन वाला तरीका।",
        "slides": [
            s("🍕", "Oil soaks into cardboard and can't be washed out.", "तेल गत्ते में सोख जाता है और धुलता नहीं।"),
            s("✂️", "Tear off the clean lid — that goes with paper.", "साफ़ ढक्कन फाड़ लें — वह कागज़ में जाएगा।"),
            s("🥬", "The greasy bottom goes to wet waste or compost.", "तेल वाला निचला हिस्सा गीले कचरे या कम्पोस्ट में।"),
        ],
        "quiz": [
            q("What do you do with the greasy part of a pizza box?", "पिज़्ज़ा बॉक्स के तेल वाले हिस्से का क्या करें?",
              [("Paper recycling", "कागज़ रीसायकलिंग"), ("Wet waste / compost", "गीला कचरा / कम्पोस्ट"),
               ("E-waste", "ई-कचरा")], 1,
              "Greasy cardboard spoils paper recycling but composts well.",
              "तेल वाला गत्ता कागज़ रीसायकलिंग खराब करता है, पर कम्पोस्ट में ठीक है।"),
        ],
    },
    {
        "slug": "aluminium-cans", "category_slug": "metal", "emoji": "🥫", "duration_sec": 40,
        "title": "How aluminium cans are recycled", "title_hi": "एल्युमिनियम कैन कैसे रीसायकल होते हैं",
        "description": "Why a can is one of the best things you can recycle.",
        "description_hi": "कैन रीसायकल करने के लिए सबसे अच्छी चीज़ों में से एक क्यों है।",
        "slides": [
            s("🥫", "Aluminium can be melted and reused again and again without getting worse.",
              "एल्युमिनियम को बार-बार पिघलाकर दोबारा इस्तेमाल किया जा सकता है, गुणवत्ता घटती नहीं।"),
            s("⚡", "Recycling aluminium uses far less energy than making it from ore.",
              "एल्युमिनियम रीसायकल करने में नया बनाने से बहुत कम ऊर्जा लगती है।"),
            s("🚿", "Just empty and rinse it. Don't stuff rubbish inside.",
              "बस खाली करके धो लें। अंदर कचरा न भरें।"),
        ],
        "quiz": [
            q("How many times can aluminium be recycled?", "एल्युमिनियम कितनी बार रीसायकल हो सकता है?",
              [("Once", "एक बार"), ("Twice", "दो बार"), ("Again and again", "बार-बार")], 2,
              "Aluminium keeps its quality through many recycling rounds.",
              "एल्युमिनियम कई बार रीसायकल होने पर भी अपनी गुणवत्ता बनाए रखता है।"),
        ],
    },
    {
        "slug": "glass-safe", "category_slug": "glass", "emoji": "🍾", "duration_sec": 35,
        "title": "Broken glass: wrap, label, protect", "title_hi": "टूटा काँच: लपेटें, लिखें, बचाएँ",
        "description": "Keep your collector safe from cuts.", "description_hi": "संग्रह साथी को चोट से बचाएँ।",
        "slides": [
            s("🍾", "Bottles and jars go with glass after a quick rinse.", "बोतलें और जार हल्का धोकर काँच में।"),
            s("📰", "Broken glass: wrap it in thick newspaper or a box.", "टूटा काँच: मोटे अख़बार या डिब्बे में लपेटें।"),
            s("✍️", "Write SHARP on it. Someone's hands will thank you.", "उस पर 'धारदार' लिखें। किसी के हाथ बच जाएँगे।"),
            s("🪞", "Mirrors, window glass and crockery don't go with bottles.",
              "शीशा, खिड़की का काँच और क्रॉकरी बोतलों के साथ नहीं जाते।"),
        ],
        "quiz": [
            q("What should you do with broken glass?", "टूटे काँच का क्या करें?",
              [("Put it loose in a bag", "थैली में खुला डालें"), ("Wrap it and label it SHARP",
               "लपेटकर 'धारदार' लिखें"), ("Mix it with paper", "कागज़ में मिलाएँ")], 1,
              "Wrapping and labelling protects collectors from cuts.",
              "लपेटने और लिखने से संग्रह साथी कटने से बचते हैं।"),
        ],
    },
    {
        "slug": "old-clothes", "category_slug": "textile", "emoji": "👕", "duration_sec": 45,
        "title": "What happens to your old clothes?", "title_hi": "आपके पुराने कपड़ों का क्या होता है?",
        "description": "Wear, share, then recycle — in that order.", "description_hi": "पहनें, बाँटें, फिर रीसायकल करें।",
        "slides": [
            s("👕", "Wearable clothes are donated — to families, schools and shelters.",
              "पहनने लायक कपड़े दान होते हैं — परिवारों, स्कूलों और आश्रयों को।"),
            s("✂️", "Worn-out clothes become cleaning rags or are shredded into fibre.",
              "फटे कपड़ों से पोछे बनते हैं या उनसे रेशा निकाला जाता है।"),
            s("🧵", "That fibre becomes stuffing, insulation or new yarn.", "उस रेशे से भराई, इन्सुलेशन या नया धागा बनता है।"),
            s("💧", "Always wash and dry clothes first. Wet clothes grow mould.",
              "पहले कपड़े धोकर सुखाएँ। गीले कपड़ों में फफूंद लगती है।"),
        ],
        "quiz": [
            q("Can you recycle old clothes?", "क्या पुराने कपड़े रीसायकल हो सकते हैं?",
              [("Yes — donate wearable ones, recycle torn ones", "हाँ — पहनने लायक दान, फटे रीसायकल"),
               ("No, they go in the dustbin", "नहीं, कूड़ेदान में जाते हैं")], 0,
              "Clothes can be reused or recycled into fibre.", "कपड़े दोबारा इस्तेमाल या रेशे में रीसायकल हो सकते हैं।"),
        ],
    },
    {
        "slug": "donate-dont-dump", "category_slug": "general", "emoji": "🎁", "duration_sec": 40,
        "title": "Donate, don't dump: books, clothes and toys", "title_hi": "फेंकें नहीं, दान करें: किताबें, कपड़े, खिलौने",
        "description": "Some 'waste' is still a gift. Here's how Swacchify sends it to schools.",
        "description_hi": "कुछ 'कचरा' अब भी तोहफ़ा है। स्वच्छिफ़ाई इसे स्कूलों तक कैसे पहुँचाता है।",
        "slides": [
            s("📚", "Textbooks, storybooks and notebooks with blank pages help students.",
              "पाठ्यपुस्तकें, कहानी की किताबें और खाली पन्नों वाली कॉपियाँ बच्चों के काम आती हैं।"),
            s("🧸", "Working toys and clean clothes can go to anganwadis and shelters.",
              "चालू खिलौने और साफ़ कपड़े आँगनवाड़ी और आश्रयों में जा सकते हैं।"),
            s("🚚", "Choose 'Donate' when you schedule a pickup — we route it to partner schools.",
              "पिकअप बुक करते समय 'दान' चुनें — हम इसे साथी स्कूलों तक पहुँचाते हैं।"),
        ],
        "quiz": [
            q("A storybook in good condition should be…", "अच्छी हालत की कहानी की किताब को…",
              [("Recycled as paper", "कागज़ में रीसायकल करें"), ("Donated", "दान करें"), ("Burned", "जलाएँ")], 1,
              "Reuse comes before recycling.", "रीसायकल से पहले दोबारा इस्तेमाल।"),
        ],
    },
    {
        "slug": "what-we-dont-take", "category_slug": "other", "emoji": "🚫", "duration_sec": 45,
        "title": "Thermocol & wet wipes: why we don't collect them", "title_hi": "थर्माकोल और वेट वाइप्स: हम इन्हें क्यों नहीं लेते",
        "description": "Two everyday items that can't be recycled, and simple swaps.",
        "description_hi": "दो आम चीज़ें जो रीसायकल नहीं होतीं, और उनके आसान विकल्प।",
        "slides": [
            s("⬜", "Thermocol is almost all air — too costly to transport, and very few recyclers take it.",
              "थर्माकोल लगभग पूरी हवा है — ढोना महँगा है, और बहुत कम रीसायकलर इसे लेते हैं।"),
            s("🔥", "Never burn thermocol — its smoke is toxic.", "थर्माकोल कभी न जलाएँ — इसका धुआँ ज़हरीला है।"),
            s("🧻", "Wet wipes contain plastic fibres. They can't be recycled and they block drains.",
              "वेट वाइप्स में प्लास्टिक रेशे होते हैं। ये रीसायकल नहीं होते और नालियाँ जाम करते हैं।"),
            s("🍃", "Swap: steel or leaf plates instead of thermocol, a washable cloth instead of wipes.",
              "विकल्प: थर्माकोल की जगह स्टील या पत्तल, वाइप्स की जगह धुलने वाला कपड़ा।"),
        ],
        "quiz": [
            q("Should thermocol go with your Swacchify dry-waste pickup?", "क्या थर्माकोल स्वच्छिफ़ाई पिकअप में दें?",
              [("Yes", "हाँ"), ("No — reuse it or give to municipal collection", "नहीं — दोबारा इस्तेमाल करें या नगर निगम को दें")],
              1, "Swacchify doesn't collect thermocol. Reuse it or use municipal collection.",
              "स्वच्छिफ़ाई थर्माकोल नहीं लेता। दोबारा इस्तेमाल करें या नगर निगम को दें।"),
            q("Can wet wipes be flushed?", "क्या वेट वाइप्स फ़्लश कर सकते हैं?",
              [("Yes", "हाँ"), ("No", "नहीं")], 1,
              "They don't break down and block drains.", "ये गलते नहीं और नालियाँ जाम करते हैं।"),
        ],
    },
    {
        "slug": "segregation-mistakes", "category_slug": "general", "emoji": "❌", "duration_sec": 75,
        "title": "5 common segregation mistakes", "title_hi": "कचरा अलग करने की 5 आम गलतियाँ",
        "description": "Small slips that send good recyclables to a landfill.",
        "description_hi": "छोटी गलतियाँ जो अच्छे रीसायकल सामान को लैंडफिल भेज देती हैं।",
        "slides": [
            s("🥛", "1. Milk packets with milk still inside.", "1. दूध बची हुई थैलियाँ।"),
            s("🍕", "2. Greasy pizza boxes in paper.", "2. तेल वाले पिज़्ज़ा बॉक्स कागज़ में।"),
            s("🔋", "3. Batteries thrown in the dustbin.", "3. बैटरी कूड़ेदान में।"),
            s("🛍️", "4. Wet waste tied up inside the dry-waste bag.", "4. सूखे कचरे की थैली में गीला कचरा।"),
            s("💡", "5. CFL bulbs mixed with glass bottles.", "5. सीएफ़एल बल्ब काँच की बोतलों के साथ।"),
        ],
        "quiz": [
            q("Which is a segregation mistake?", "इनमें से कौन-सी गलती है?",
              [("Rinsing a milk packet", "दूध की थैली धोना"), ("Putting a CFL bulb with glass bottles",
               "सीएफ़एल बल्ब को काँच की बोतलों के साथ रखना"), ("Flattening boxes", "डिब्बे चपटे करना")], 1,
              "CFLs are e-waste — they contain mercury.", "सीएफ़एल ई-कचरा है — इसमें पारा होता है।"),
        ],
    },
]

TIPS = [
    ("Keep batteries separate from normal household waste.", "बैटरियों को सामान्य घरेलू कचरे से अलग रखें।", "ewaste"),
    ("Rinse milk packets before putting them with plastic.", "दूध की थैलियाँ प्लास्टिक में डालने से पहले धो लें।", "plastic"),
    ("Flatten cardboard boxes — they take a quarter of the space.", "गत्ते के डिब्बे चपटे करें — जगह चौथाई रह जाती है।", "paper"),
    ("Tear off the greasy part of a pizza box; recycle the clean lid.", "पिज़्ज़ा बॉक्स का तेल वाला हिस्सा फाड़ें; साफ़ ढक्कन रीसायकल करें।", "paper"),
    ("Wrap broken glass in newspaper and write SHARP on it.", "टूटे काँच को अख़बार में लपेटें और 'धारदार' लिखें।", "glass"),
    ("Anything with a plug or battery is e-waste.", "जिसमें प्लग या बैटरी हो, वह ई-कचरा है।", "ewaste"),
    ("Donate clothes that can still be worn; wash them first.", "पहनने लायक कपड़े धोकर दान करें।", "textile"),
    ("Carry a cloth bag and say no to plastic carry bags.", "कपड़े का थैला रखें और प्लास्टिक थैली को ना कहें।", "plastic"),
    ("Empty spray cans completely before recycling them.", "स्प्रे कैन रीसायकल करने से पहले पूरी तरह खाली करें।", "metal"),
    ("Keep a small box for dead batteries and old chargers.", "पुरानी बैटरी और चार्जर के लिए एक छोटा डिब्बा रखें।", "ewaste"),
    ("Never burn waste — the smoke harms your family's lungs.", "कचरा कभी न जलाएँ — धुआँ परिवार के फेफड़ों को नुकसान पहुँचाता है।", None),
    ("Vegetable peels make great compost for your plants.", "सब्ज़ियों के छिलकों से पौधों के लिए बढ़िया खाद बनती है।", "other"),
    ("Wet wipes don't break down — a washable cloth is better.", "वेट वाइप्स गलते नहीं — धुलने वाला कपड़ा बेहतर है।", "other"),
    ("Factory-reset old phones before giving them as e-waste.", "पुराना फ़ोन ई-कचरे में देने से पहले फ़ैक्टरी रीसेट करें।", "ewaste"),
    ("Dry waste should be clean and dry — that's the golden rule.", "सूखा कचरा साफ़ और सूखा होना चाहिए — यही सुनहरा नियम है।", None),
    ("Books in good condition can help a student — donate them.", "अच्छी हालत की किताबें किसी छात्र के काम आ सकती हैं — दान करें।", "paper"),
    ("Keep CFL bulbs whole; they contain a little mercury.", "सीएफ़एल बल्ब साबुत रखें; इनमें थोड़ा पारा होता है।", "ewaste"),
    ("Tie old shoes together in pairs before giving them away.", "पुराने जूते देने से पहले जोड़ी में बाँधें।", "textile"),
    ("Scrunch clean aluminium foil into a ball before recycling it.", "साफ़ एल्युमिनियम फ़ॉयल को गोला बनाकर रीसायकल करें।", "metal"),
    ("Swap thermocol plates for steel or leaf plates at parties.", "पार्टी में थर्माकोल की जगह स्टील या पत्तल की प्लेट लें।", "other"),
]

CHALLENGES = [
    ("Separate recyclable waste before disposing of your household waste today.", "आज घरेलू कचरा फेंकने से पहले रीसायकल होने वाला कचरा अलग करें।"),
    ("Find three batteries or old chargers at home and put them in one box.", "घर में तीन बैटरियाँ या पुराने चार्जर ढूँढें और एक डिब्बे में रखें।"),
    ("Rinse and dry every milk packet you use today.", "आज इस्तेमाल हुई हर दूध की थैली धोकर सुखाएँ।"),
    ("Say no to one plastic carry bag today.", "आज एक प्लास्टिक थैली को ना कहें।"),
    ("Flatten all cardboard boxes in your home.", "घर के सभी गत्ते के डिब्बे चपटे करें।"),
    ("Teach one family member the plug-and-battery rule.", "परिवार के एक सदस्य को प्लग-और-बैटरी नियम सिखाएँ।"),
    ("Pick out one set of clothes you can donate.", "दान करने लायक कपड़ों का एक सेट अलग करें।"),
]

REWARDS = [
    {"title": "Cloth shopping bag", "title_hi": "कपड़े का थैला", "emoji": "👜", "points_cost": 150,
     "description": "A sturdy, reusable cotton bag delivered with your next pickup."},
    {"title": "Home compost starter kit", "title_hi": "घरेलू कम्पोस्ट किट", "emoji": "🪴", "points_cost": 600,
     "description": "Bin, coco-peat and a guide to turn kitchen waste into compost."},
    {"title": "Plant a sapling", "title_hi": "एक पौधा लगाएँ", "emoji": "🌳", "points_cost": 250,
     "description": "We plant a native sapling with a community partner in your name."},
    {"title": "Steel water bottle", "title_hi": "स्टील की पानी बोतल", "emoji": "🥤", "points_cost": 400,
     "description": "Say goodbye to single-use bottles."},
    {"title": "Donate school supplies", "title_hi": "स्कूल सामग्री दान करें", "emoji": "✏️", "points_cost": 200,
     "description": "Your points fund notebooks and pencils for a partner school."},
]

BADGES = [
    {"slug": "waste-beginner", "name": "Waste Beginner", "name_hi": "शुरुआती", "emoji": "🌱",
     "description": "Asked your first question or finished your first lesson."},
    {"slug": "green-starter", "name": "Green Starter", "name_hi": "हरित शुरुआत", "emoji": "🍃",
     "description": "Completed your first verified pickup."},
    {"slug": "habit-builder", "name": "Recycling Habit Builder", "name_hi": "आदत निर्माता", "emoji": "🔁",
     "description": "Kept a 7-day streak."},
    {"slug": "ewaste-responsible", "name": "E-Waste Responsible User", "name_hi": "ज़िम्मेदार ई-कचरा", "emoji": "🔋",
     "description": "Handed over e-waste through a verified pickup."},
    {"slug": "eco-household", "name": "Eco Household", "name_hi": "इको घर", "emoji": "🏡",
     "description": "Your household diverted 25 kg of material."},
    {"slug": "champion", "name": "Swacchify Champion", "name_hi": "स्वच्छिफ़ाई चैंपियन", "emoji": "🏆",
     "description": "Completed 10 verified pickups."},
    {"slug": "earth-guardian", "name": "Earth Guardian", "name_hi": "पृथ्वी रक्षक", "emoji": "🌍",
     "description": "Finished every lesson and diverted 50 kg."},
]
