"""initial schema

Revision ID: 4678d64bae81
Revises: 
Create Date: 2026-09-19 16:27:37.022341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4678d64bae81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hi', sa.Text(), nullable=True),
    sa.Column('category_slug', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_content'))
    )
    with op.batch_alter_table('daily_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_content_kind'), ['kind'], unique=False)

    op.create_table('dropoff_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('accepted_categories', sa.JSON(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('hours', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dropoff_points'))
    )
    with op.batch_alter_table('dropoff_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dropoff_points_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dropoff_points_kind'), ['kind'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('title_hi', sa.String(length=160), nullable=True),
    sa.Column('category_slug', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_hi', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('slides', sa.JSON(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_category_slug'), ['category_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_slug'), ['slug'], unique=True)

    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('title_hi', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rewards'))
    )
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rewards_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_code', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notification_prefs', sa.JSON(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_last_active_on'), ['last_active_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_public_code'), ['public_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('waste_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('name_hi', sa.String(length=60), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('short', sa.String(length=200), nullable=False),
    sa.Column('short_hi', sa.String(length=200), nullable=False),
    sa.Column('collectable', sa.Boolean(), nullable=False),
    sa.Column('donatable', sa.Boolean(), nullable=False),
    sa.Column('points_per_kg', sa.Integer(), nullable=False),
    sa.Column('partner_rate_per_kg', sa.Float(), nullable=False),
    sa.Column('co2e_factor', sa.Float(), nullable=False),
    sa.Column('guidance', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_categories'))
    )
    with op.batch_alter_table('waste_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waste_categories_slug'), ['slug'], unique=True)

    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('line1', sa.String(length=200), nullable=False),
    sa.Column('line2', sa.String(length=200), nullable=True),
    sa.Column('landmark', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_addresses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_addresses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_user_id'), ['user_id'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_key', sa.String(length=48), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversations'))
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('collection_partners',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=40), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True),
    sa.Column('service_radius_km', sa.Float(), nullable=False),
    sa.Column('base_lat', sa.Float(), nullable=False),
    sa.Column('base_lng', sa.Float(), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('id_proof_url', sa.String(length=500), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collection_partners_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_collection_partners'))
    )
    with op.batch_alter_table('collection_partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_partners_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_partners_verification_status'), ['verification_status'], unique=False)

    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_activity_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_activity')),
    sa.UniqueConstraint('user_id', 'day', 'kind', name=op.f('uq_daily_activity_user_id'))
    )
    with op.batch_alter_table('daily_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_activity_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_activity_user_id'), ['user_id'], unique=False)

    op.create_table('habit_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('longest', sa.Integer(), nullable=False),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_habit_streaks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habit_streaks')),
    sa.UniqueConstraint('user_id', 'kind', name=op.f('uq_habit_streaks_user_id'))
    )
    with op.batch_alter_table('habit_streaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_streaks_user_id'), ['user_id'], unique=False)

    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('invite_code', sa.String(length=12), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_households_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households'))
    )
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_households_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_households_invite_code'), ['invite_code'], unique=True)

    op.create_table('industry_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('category_slug', sa.String(length=32), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('allocated_kg', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('processing_method', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['users.id'], name=op.f('fk_industry_orders_industry_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industry_orders'))
    )
    with op.batch_alter_table('industry_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_industry_orders_category_slug'), ['category_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_industry_orders_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_industry_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_industry_orders_industry_id'), ['industry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_industry_orders_status'), ['status'], unique=False)

    op.create_table('learning_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_learning_progress_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_progress')),
    sa.UniqueConstraint('user_id', 'lesson_id', name=op.f('uq_learning_progress_user_id'))
    )
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_resets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_resets')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_resets_token_hash'))
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payee_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payee_id'], ['users.id'], name=op.f('fk_payments_payee_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payee_id'), ['payee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_reference'), ['reference'], unique=False)

    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('pass_pct', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_quizzes_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quizzes')),
    sa.UniqueConstraint('lesson_id', name=op.f('uq_quizzes_lesson_id'))
    )
    op.create_table('recycling_industries',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=160), nullable=False),
    sa.Column('authorization_number', sa.String(length=80), nullable=True),
    sa.Column('accepted_categories', sa.JSON(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recycling_industries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_recycling_industries'))
    )
    with op.batch_alter_table('recycling_industries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recycling_industries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recycling_industries_verification_status'), ['verification_status'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('reward_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reward_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reward_transactions'))
    )
    with op.batch_alter_table('reward_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_transactions_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_transactions_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_slug', sa.String(length=40), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_badges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_badges')),
    sa.UniqueConstraint('user_id', 'badge_slug', name=op.f('uq_user_badges_user_id'))
    )
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badges_user_id'), ['user_id'], unique=False)

    op.create_table('waste_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['waste_categories.id'], name=op.f('fk_waste_subcategories_category_id_waste_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_subcategories')),
    sa.UniqueConstraint('slug', name=op.f('uq_waste_subcategories_slug'))
    )
    with op.batch_alter_table('waste_subcategories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waste_subcategories_category_id'), ['category_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('matched_item_slug', sa.String(length=64), nullable=True),
    sa.Column('category_slug', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Integer(), nullable=True),
    sa.Column('feedback_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_messages_conversation_id_ai_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_category_slug'), ['category_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_intent'), ['intent'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_matched_item_slug'), ['matched_item_slug'], unique=False)

    op.create_table('customer_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_customer_profiles_household_id_households'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customer_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_customer_profiles'))
    )
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_profiles_household_id'), ['household_id'], unique=False)

    op.create_table('household_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('relation', sa.String(length=40), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_household_members_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_household_members_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_members'))
    )
    with op.batch_alter_table('household_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_members_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_household_members_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_household_members_user_id'), ['user_id'], unique=False)

    op.create_table('industry_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=24), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['users.id'], name=op.f('fk_industry_transactions_industry_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['industry_orders.id'], name=op.f('fk_industry_transactions_order_id_industry_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industry_transactions')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_industry_transactions_invoice_number'))
    )
    with op.batch_alter_table('industry_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_industry_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_industry_transactions_industry_id'), ['industry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_industry_transactions_order_id'), ['order_id'], unique=False)

    op.create_table('pickup_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('address_text', sa.Text(), nullable=False),
    sa.Column('landmark', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('estimated_total_kg', sa.Float(), nullable=False),
    sa.Column('actual_total_kg', sa.Float(), nullable=True),
    sa.Column('proof_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('fk_pickup_requests_address_id_addresses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_pickup_requests_customer_id_users')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_pickup_requests_household_id_households'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], name=op.f('fk_pickup_requests_partner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pickup_requests'))
    )
    with op.batch_alter_table('pickup_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pickup_requests_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_requests_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_pickup_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_requests_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_requests_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_requests_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_requests_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_requests_status'), ['status'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_attempts_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quiz_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempts'))
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_hi', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('explanation_hi', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_questions_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_questions'))
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('waste_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=True),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('collectable', sa.Boolean(), nullable=False),
    sa.Column('donatable', sa.Boolean(), nullable=False),
    sa.Column('what_to_do', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('what_not_to_do', sa.Text(), nullable=False),
    sa.Column('prep_tips', sa.Text(), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('common_mistakes', sa.Text(), nullable=True),
    sa.Column('reuse_tip', sa.Text(), nullable=True),
    sa.Column('local_note', sa.Text(), nullable=True),
    sa.Column('clarify', sa.JSON(), nullable=True),
    sa.Column('related', sa.JSON(), nullable=False),
    sa.Column('lesson_slug', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['waste_categories.id'], name=op.f('fk_waste_items_category_id_waste_categories')),
    sa.ForeignKeyConstraint(['subcategory_id'], ['waste_subcategories.id'], name=op.f('fk_waste_items_subcategory_id_waste_subcategories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_items'))
    )
    with op.batch_alter_table('waste_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waste_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waste_items_slug'), ['slug'], unique=True)

    op.create_table('impact_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('category_slug', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('co2e_kg_est', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_impact_records_household_id_households'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickup_requests.id'], name=op.f('fk_impact_records_pickup_id_pickup_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_impact_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_records'))
    )
    with op.batch_alter_table('impact_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impact_records_category_slug'), ['category_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_impact_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_impact_records_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_impact_records_pickup_id'), ['pickup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_impact_records_user_id'), ['user_id'], unique=False)

    op.create_table('pickup_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], name=op.f('fk_pickup_assignments_partner_id_users')),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickup_requests.id'], name=op.f('fk_pickup_assignments_pickup_id_pickup_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pickup_assignments'))
    )
    with op.batch_alter_table('pickup_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pickup_assignments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_assignments_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_assignments_pickup_id'), ['pickup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_assignments_status'), ['status'], unique=False)

    op.create_table('pickup_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('category_slug', sa.String(length=32), nullable=False),
    sa.Column('estimated_kg', sa.Float(), nullable=False),
    sa.Column('actual_kg', sa.Float(), nullable=True),
    sa.Column('verified_kg', sa.Float(), nullable=True),
    sa.Column('allocated_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickup_requests.id'], name=op.f('fk_pickup_items_pickup_id_pickup_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pickup_items'))
    )
    with op.batch_alter_table('pickup_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pickup_items_category_slug'), ['category_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_items_pickup_id'), ['pickup_id'], unique=False)

    op.create_table('pickup_status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_pickup_status_events_actor_id_users')),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickup_requests.id'], name=op.f('fk_pickup_status_events_pickup_id_pickup_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pickup_status_events'))
    )
    with op.batch_alter_table('pickup_status_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pickup_status_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_status_events_pickup_id'), ['pickup_id'], unique=False)

    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('ratee_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickup_requests.id'], name=op.f('fk_ratings_pickup_id_pickup_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ratee_id'], ['users.id'], name=op.f('fk_ratings_ratee_id_users')),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], name=op.f('fk_ratings_rater_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings'))
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_pickup_id'), ['pickup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_ratee_id'), ['ratee_id'], unique=False)

    op.create_table('waste_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=False),
    sa.Column('total_kg', sa.Float(), nullable=False),
    sa.Column('segregation_quality', sa.String(length=8), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickup_requests.id'], name=op.f('fk_waste_verifications_pickup_id_pickup_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_waste_verifications_verified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_verifications')),
    sa.UniqueConstraint('pickup_id', name=op.f('uq_waste_verifications_pickup_id'))
    )
    with op.batch_alter_table('waste_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waste_verifications_created_at'), ['created_at'], unique=False)

    op.create_table('lot_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('pickup_item_id', sa.Integer(), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['industry_orders.id'], name=op.f('fk_lot_allocations_order_id_industry_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pickup_item_id'], ['pickup_items.id'], name=op.f('fk_lot_allocations_pickup_item_id_pickup_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lot_allocations'))
    )
    with op.batch_alter_table('lot_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lot_allocations_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_allocations_pickup_item_id'), ['pickup_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lot_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lot_allocations_pickup_item_id'))
        batch_op.drop_index(batch_op.f('ix_lot_allocations_order_id'))

    op.drop_table('lot_allocations')
    with op.batch_alter_table('waste_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waste_verifications_created_at'))

    op.drop_table('waste_verifications')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_ratee_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_pickup_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_created_at'))

    op.drop_table('ratings')
    with op.batch_alter_table('pickup_status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pickup_status_events_pickup_id'))
        batch_op.drop_index(batch_op.f('ix_pickup_status_events_created_at'))

    op.drop_table('pickup_status_events')
    with op.batch_alter_table('pickup_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pickup_items_pickup_id'))
        batch_op.drop_index(batch_op.f('ix_pickup_items_category_slug'))

    op.drop_table('pickup_items')
    with op.batch_alter_table('pickup_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pickup_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_pickup_assignments_pickup_id'))
        batch_op.drop_index(batch_op.f('ix_pickup_assignments_partner_id'))
        batch_op.drop_index(batch_op.f('ix_pickup_assignments_created_at'))

    op.drop_table('pickup_assignments')
    with op.batch_alter_table('impact_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impact_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_impact_records_pickup_id'))
        batch_op.drop_index(batch_op.f('ix_impact_records_household_id'))
        batch_op.drop_index(batch_op.f('ix_impact_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_impact_records_category_slug'))

    op.drop_table('impact_records')
    with op.batch_alter_table('waste_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waste_items_slug'))
        batch_op.drop_index(batch_op.f('ix_waste_items_category_id'))

    op.drop_table('waste_items')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_quiz_id'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_quiz_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_created_at'))

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('pickup_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pickup_requests_status'))
        batch_op.drop_index(batch_op.f('ix_pickup_requests_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_pickup_requests_partner_id'))
        batch_op.drop_index(batch_op.f('ix_pickup_requests_household_id'))
        batch_op.drop_index(batch_op.f('ix_pickup_requests_customer_id'))
        batch_op.drop_index(batch_op.f('ix_pickup_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_pickup_requests_code'))
        batch_op.drop_index(batch_op.f('ix_pickup_requests_city'))

    op.drop_table('pickup_requests')
    with op.batch_alter_table('industry_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_industry_transactions_order_id'))
        batch_op.drop_index(batch_op.f('ix_industry_transactions_industry_id'))
        batch_op.drop_index(batch_op.f('ix_industry_transactions_created_at'))

    op.drop_table('industry_transactions')
    with op.batch_alter_table('household_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_household_members_household_id'))
        batch_op.drop_index(batch_op.f('ix_household_members_created_at'))

    op.drop_table('household_members')
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_profiles_household_id'))
        batch_op.drop_index(batch_op.f('ix_customer_profiles_created_at'))

    op.drop_table('customer_profiles')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_matched_item_slug'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_intent'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_category_slug'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('waste_subcategories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waste_subcategories_category_id'))

    op.drop_table('waste_subcategories')
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badges_user_id'))

    op.drop_table('user_badges')
    with op.batch_alter_table('reward_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_reward_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_reward_transactions_source'))
        batch_op.drop_index(batch_op.f('ix_reward_transactions_reference'))
        batch_op.drop_index(batch_op.f('ix_reward_transactions_created_at'))

    op.drop_table('reward_transactions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_created_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('recycling_industries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recycling_industries_verification_status'))
        batch_op.drop_index(batch_op.f('ix_recycling_industries_created_at'))

    op.drop_table('recycling_industries')
    op.drop_table('quizzes')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_reference'))
        batch_op.drop_index(batch_op.f('ix_payments_payee_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))

    op.drop_table('payments')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_resets_created_at'))

    op.drop_table('password_resets')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_lesson_id'))

    op.drop_table('learning_progress')
    with op.batch_alter_table('industry_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_industry_orders_status'))
        batch_op.drop_index(batch_op.f('ix_industry_orders_industry_id'))
        batch_op.drop_index(batch_op.f('ix_industry_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_industry_orders_code'))
        batch_op.drop_index(batch_op.f('ix_industry_orders_category_slug'))

    op.drop_table('industry_orders')
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_households_invite_code'))
        batch_op.drop_index(batch_op.f('ix_households_created_at'))

    op.drop_table('households')
    with op.batch_alter_table('habit_streaks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_streaks_user_id'))

    op.drop_table('habit_streaks')
    with op.batch_alter_table('daily_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_activity_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_activity_day'))

    op.drop_table('daily_activity')
    with op.batch_alter_table('collection_partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_partners_verification_status'))
        batch_op.drop_index(batch_op.f('ix_collection_partners_created_at'))

    op.drop_table('collection_partners')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_created_at'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_user_id'))
        batch_op.drop_index(batch_op.f('ix_addresses_created_at'))

    op.drop_table('addresses')
    with op.batch_alter_table('waste_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waste_categories_slug'))

    op.drop_table('waste_categories')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_public_code'))
        batch_op.drop_index(batch_op.f('ix_users_last_active_on'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rewards_created_at'))

    op.drop_table('rewards')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_slug'))
        batch_op.drop_index(batch_op.f('ix_lessons_created_at'))
        batch_op.drop_index(batch_op.f('ix_lessons_category_slug'))

    op.drop_table('lessons')
    with op.batch_alter_table('dropoff_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dropoff_points_kind'))
        batch_op.drop_index(batch_op.f('ix_dropoff_points_created_at'))

    op.drop_table('dropoff_points')
    with op.batch_alter_table('daily_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_content_kind'))

    op.drop_table('daily_content')
    # ### end Alembic commands ###
